apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    provider: helm
  name: ingresses.aws.platform.upbound.io
spec:
  compositeTypeRef:
    apiVersion: aws.platform.upbound.io/v1alpha1
    kind: Ingress
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-configuration-aws-lb-controllerawslbcontroller-py
    step: awslbcontroller-py
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
