apiVersion: aws.platform.upbound.io/v1alpha1
kind: AWSLBController
metadata:
  name: configuration-aws-lb-controller
  labels:
    platform.upbound.io/deletion-ordering: enabled
  namespace: default
spec:
  parameters:
    region: us-west-2
    vpcId: vpc-12345678
    helm:
      providerConfigName: configuration-aws-lb-controller
    clusterNameSelector:
      matchLabels:
        crossplane.io/composite: configuration-aws-lb-controller
